name: xecosystem
description: Opinionated Flutter UI + API ecosystem. Zero boilerplate, full freedom.
version: 1.0.0
homepage: https://github.com/sagar9098/xecosystem
repository: https://github.com/sagar9098/xecosystem
issue_tracker: https://github.com/sagar9098/xecosystem/issues
screenshots:
  - description: Login Screen
    path: screenshots/login.png
  - description: Dashboard
    path: screenshots/dashboard.png
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0